### PR TITLE
GN-4399: check if related road-marking or traffic-light has undefined definition

### PR DESCRIPTION
**Pull request by elpoelma**
## Overview
This PR solves an issue where an error was thrown when search for related road-markings. This turned out to be an issue of a missing nullcheck on `roadMarking.definition`. This PR also adds nullchecks to  `trafficLight.definition` to prevent a similar issue.

##### connected issues and PRs:
Jira: https://binnenland.atlassian.net/browse/GN-4399?atlOrigin=eyJpIjoiNjkyNTIzYTA4NDQwNGQwNzk5ZTMyM2ZlNjBlY2Y3MjQiLCJwIjoiaiJ9

### How to test/reproduce
- Open a road-sign/road-marking/traffic-light
- Search through the list of related road-markings, the `undefined` error should no longer be thrown. 

### Checks PR readiness
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by x-m-el — APPROVED** [review]
looks good and fixes the bug.
It is a bit weird it does filtering on the definition though, because as far as I can see, the definition can't be changed in the form, except for traffic lights.
So this will just make it so new roadmarkings can never be searched (because they'll always return undefined). So they can never be added somewhere...

So this fixes the bug, but not the core issue I think?

I'll leave it up to you if this should be fixed here or added as a separate ticket.

**Comment by abeforgit** [comment]
> looks good and fixes the bug. It is a bit weird it does filtering on the definition though, because as far as I can see, the definition can't be changed in the form, except for traffic lights. So this will just make it so new roadmarkings can never be found by searching (because they'll always return undefined). So they can never be added somewhere...
> 
> So this fixes the bug, but not the core issue I think?
> 
> I'll leave it up to you if this should be fixed here or added as a separate ticket.

you're right... christ every time I think I've seen the worst of this thing...
this is how a new road marking shows up in the list (as you mentioned its impossible to add a definition)
image

**Comment by elpoelma** [comment]
> looks good and fixes the bug. It is a bit weird it does filtering on the definition though, because as far as I can see, the definition can't be changed in the form, except for traffic lights. So this will just make it so new roadmarkings can never be found by searching (because they'll always return undefined). So they can never be added somewhere...
> 
> So this fixes the bug, but not the core issue I think?
> 
> I'll leave it up to you if this should be fixed here or added as a separate ticket.

My god, didn't even notice that. I just assumed it would be sensible. I would honestly fix that in a seperate ticket.

**Comment by elpoelma** [comment]
I created a seperate ticket for it on Jira: https://binnenland.atlassian.net/browse/GN-4463?atlOrigin=eyJpIjoiOGIyNTk0NGI2NGJmNDRkODk2ZjQyYThhZGYzZWMyYjIiLCJwIjoiaiJ9

**Pull request merged**
