### PR TITLE
GN-4353: disable search field trimming

### PR DESCRIPTION
**Pull request by elpoelma**
## Overview
This PR removes the `.trim()` call when updating the search filter based on the value of an input field. It caused issues typing spaces into the input fields.

##### connected issues and PRs:
Jira ticket: https://binnenland.atlassian.net/browse/GN-4353?atlOrigin=eyJpIjoiNmQxNjkzMGQ5OGM0NGNmYzgxOGM5YmNkNWIyY2JlYWQiLCJwIjoiaiJ9

### How to test/reproduce
Visit any of the main index pages and type text and spaces into the search-fields, the inputs should no longer be trimmed.

### Checks PR readiness
- [x] npm lint

### CODE REVIEW

**Comment by elpoelma** [comment]
In relation to https://github.com/emberjs/data/issues/8599, we could maybe take the approach mentioned in this issue (casting to `unknown` and the to an `array` when resolving hasMany relationships.

**Review by x-m-el — APPROVED** [review]
This does change the functionality (a final space *will* make the search fail for exact searched). 
However, looking at the code, providing the same functionality without the bug would need rewriting of the code, so just fixing the bug is definitely the best...
This does mean that on MOW this is not consistent: searching in a table a space will fail the search (so where you made this change), but when adding related-whatevers, a space *is* filtered away. (e.g. in the pop-out "onderborden toevoegen").
I don't like this inconsistency, but I'm not convinced it is a problem either. So I'll personally leave this decision with you.

reviewing: 
- checked if everything seemed to work as expected
- didn't see any places that were forgotten (only the inconsistency mentioned)

**Comment by elpoelma** [comment]
> This does change the functionality (a final space _will_ make the search fail for exact searched). However, looking at the code, providing the same functionality without the bug would need rewriting of the code, so just fixing the bug is definitely the best... This does mean that on MOW this is not consistent: searching in a table a space will fail the search (so where you made this change), but when adding related-whatevers, a space _is_ filtered away. (e.g. in the pop-out "onderborden toevoegen"). I don't like this inconsistency, but I'm not convinced it is a problem either. So I'll personally leave this decision with you.
> 
> reviewing:
> 
>     * checked if everything seemed to work as expected
> 
>     * didn't see any places that were forgotten (only the inconsistency mentioned)
> 
>     * I ignored your comment about the `unknown` and `array` as I'm not sure what this refers to. :)

- We could indeed removing the trimming everywhere so it is consistent. 
- On the comment: it was meant for the typescript PR, you can ignore it, I'll move it to the correct PR.

**Comment by elpoelma** [comment]
@x-m-el I removed the other usages of trimming, so it should be consistent now.

**Review by x-m-el — APPROVED** [review]
yes, feels nicer with it being consistent :+1: 

Out of scope, but interesting: the search string does not get reset when navigating the app. I could see this as a "feature" too, but it feels a bit disorienting (and the page *does* get reset, so either way the "keep your old search" isn't consistent).

I'll make an issue for it.

**Pull request merged**
